export declare const FESTAC_WARDS: readonly ["Amuwo-Odofin Ward A", "Amuwo-Odofin Ward B", "Festac Town", "Mile 2", "Satellite Town", "Apple Junction", "Agboju", "Alakija", "Kirikiri", "Ojo"];
export declare const LAGOS_LGAS: readonly ["Amuwo-Odofin", "Surulere", "Lagos Island", "Lagos Mainland", "Eti-Osa", "Ikeja", "Alimosho", "Ojo", "Badagry", "Ikorodu"];
export declare const CURRENCY = "NGN";
export declare const CURRENCY_SYMBOL = "\u20A6";
export declare const DEFAULT_LGA = "Amuwo-Odofin";
export declare const DEFAULT_STATE = "Lagos";
export declare const FESTAC_CENTER: {
    lat: number;
    lng: number;
};
export declare const DEFAULT_SEARCH_RADIUS_KM = 5;
export declare const MAX_SEARCH_RADIUS_KM = 50;
export declare const DEFAULT_PAGE_SIZE = 20;
export declare const MAX_PAGE_SIZE = 100;
export declare const MAX_IMAGE_SIZE_MB = 5;
export declare const MAX_IMAGES_PER_VENDOR = 10;
export declare const ALLOWED_IMAGE_TYPES: readonly ["image/jpeg", "image/png", "image/webp"];
export declare const MIN_RATING = 1;
export declare const MAX_RATING = 5;
export declare const MIN_BOOKING_ADVANCE_HOURS = 1;
export declare const MAX_BOOKING_ADVANCE_DAYS = 60;
export declare const BOOKING_REMINDER_HOURS_BEFORE = 24;
export declare const AI_MAX_TOKENS = 500;
export declare const AI_TEMPERATURE = 0.3;
export declare const AI_CONTEXT_WINDOW_MESSAGES = 10;
export declare const RATE_LIMIT_WINDOW_MS: number;
export declare const RATE_LIMIT_MAX_REQUESTS = 100;
export declare const OTP_RATE_LIMIT_MAX = 3;
export declare const OTP_EXPIRY_MINUTES = 10;
export declare const ERROR_CODES: {
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly INVALID_OTP: "INVALID_OTP";
    readonly EXPIRED_OTP: "EXPIRED_OTP";
    readonly INVALID_TOKEN: "INVALID_TOKEN";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly ALREADY_EXISTS: "ALREADY_EXISTS";
    readonly CONFLICT: "CONFLICT";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly INVALID_INPUT: "INVALID_INPUT";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE";
    readonly VENDOR_SUSPENDED: "VENDOR_SUSPENDED";
    readonly VENDOR_PENDING_APPROVAL: "VENDOR_PENDING_APPROVAL";
    readonly SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE";
    readonly BOOKING_CONFLICT: "BOOKING_CONFLICT";
};
//# sourceMappingURL=index.d.ts.map